document_type: ПОЯСНИТЕЛЬНАЯ ЗАПИСКА
work_kind: к курсовому проекту
title: Демонстрационная работа
discipline: Название дисциплины
document_code: ''
student: ''
supervisor: ''
faculty: ''
department: ''
city: Минск
year: '2026'
title_page: true
toc: true
