ministry: Министерство образования Республики Беларусь
university: Учреждение образования «Белорусский государственный университет информатики
  и радиоэлектроники»
faculty: ''
department: ''
work_type: ПОЯСНИТЕЛЬНАЯ ЗАПИСКА
discipline: ''
title: Демонстрационная работа
student: ''
group: ''
supervisor: ''
city: Минск
year: ''
title_page: true
toc: true
